### ISSUE TITLE
WellBet: Open & CLosed WellBets auf der gleichen Seite

### ISSUE THREAD

**Issue by diplomod** [diplomod/Geonova-new-#1]
Zweiten Banner von der Startseite unter die open bets

**Comment by lukassiedel** [comment]
done und live :)

**Comment by diplomod** [comment]
Sehr gut. 5 Kommentare:

1) Bitte an Stelle on "Expired Well Bets" sollte da stehen "Closed WellBets"

2) Die Liste der closed WellBets ist schon ziemlich lang, geht aber noch. Kann man (evtl. in der Zukunft) den Button von "See more Geobuzz" der Startseite hier nach ca 10 einsetzen? ("See more closed WellBets" - grün)

<img width="853" alt="screen shot 2016-06-13 at 20 45 23" src="https://cloud.githubusercontent.com/assets/7487883/16019153/d9451b32-31a7-11e6-8e45-d54a30025794.png">

3) Der Banner oben klebt an dem Header. Außerdem geht mir der da im Weg um. Kannst du den zweiten Banner wieder rausschmeissen und den ersten Banner an die Stelle des zweiten Setze (also zwischen die aktuellen und closed WellBets)? D.h. kein banner oben, nur zwischen drin.

4) Die Elemente der Sidebar sind verschwunden...

5) Wir müssten das Template updaten (neuen Titel, neues Hintergrundbild). Kann ich das irgendwo selber?

**Comment by lukassiedel** [comment]
1. erledigt
2. möglich ist es, ist nur ein wenig aufwand. ich hab jetzt erstmal die pagination wieder eingebaut
3. erledigt
4. gefixed
5. den Text kannst du unter Appeareance->Geonova-Settings anpassen
   das bild müsst ich wahrscheinlich austauschen, wenn du es nicht selbst auf den FTP hochladen magst. geht aber fix. ist ja in einer minute gemacht :)

**Comment by diplomod** [comment]
Merci.

1) Sowohl oben wie unten "WellBets" an Stelle von "Well Bets"
2) Muss erst mal reichen, ist aber sehr unpraktisch, weil man wieder oben bei den Running WellBets landet erst mal beim umblättern
3) passt
4) passt
5) Da kann ich nur die Überschrift anpassen, nicht den Satz darunter. Bitte den Teil "Geonova WellBet is brought to you by Atlantic Petroleum Norge." löschen. Bild muss ich noch schauen, schicke ich dann

**Comment by lukassiedel** [comment]
1. oh das war mir entgangen
2. Ich habs gefunden. der Header text geht anzupassen unter Settings->Edit header texts:
   Dazu im Feld "Destination Tag" den Tag "well_bet" angeben, bei Text einfach deinen Gewünschten text und wenn noch gewünscht die url "http://www.geonova.no/well-bet/about-wellbet/"  für den more-information-button eintragen und die checkbox aktivieren
