### ISSUE TITLE
News Schedulen löst keine Mail aus

### ISSUE THREAD

**Issue by diplomod** [diplomod/Geonova-new-#10]
Hab heute eine news gescheduled, es wurde aber glaube ich keine Mail rausgeschickt:

http://www.geonova.no/geobuzz/news-page/early-bird/

<img width="389" alt="screen shot 2016-08-31 at 09 11 04" src="https://cloud.githubusercontent.com/assets/7487883/18129535/6f90f8b0-6f8b-11e6-8f7b-4b802d824896.png">

**Comment by lukassiedel** [comment]
done

**Comment by philipdomann** [comment]
Mega

Am 23. Oktober 2016 23:20:26 MESZ, schrieb Lukas Siedel notifications@github.com:

> done
> 
> ## 
> 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/diplomod/Geonova-new-/issues/10#issuecomment-255615160

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by diplomod** [comment]
Top - schon auf Live?
