### ISSUE TITLE
Übersicht Server

### ISSUE THREAD

**Issue by diplomod** [diplomod/Geonova-new-#11]
Ich bräuchte eine Übersicht der Projekte die auf dem Geonova Server liegen.

Ist das
- geonova.no
- ncsprospects.com
- hydrocarbonhabitats.no
- ncs-exploration.com

??

Ausserdem könntet ihr prüfen, ob wir geo365.no realistischerweise ebefalls auf dem Server laufen lassen können - hängt zusammen mit dem issue bei geo365 mit dem Speed
https://github.com/diplomod/geo365/issues/151

**Comment by philipdomann** [comment]
geonova.no, ncsprospects.com und nordryggstien.no liegen drauf. Und ja man könnte geo365.no dort laufen lassen. Für einen Umzug würde ich 4-5h veranschlagen.

**Comment by diplomod** [comment]
OK - weisst du, wo hydrocarbonhabitats.no und ncs-exploration.com liegen?

Ein Umzug von geo365.no macht Sinn, wenn der Server der Grund dafür ist, dass es so langsam läuft. Das müssen wir erst herausfinden, dann kann ich das entscheiden.
Aber grundsätzlich ist es ja quatsch, 2 Server laufen zu lassen.
Es sei denn, der eine fällt mal aus. Wie ist das einzuschätzen bei Strato? Weil in dem Fall wäre alles dicht...
