### ISSUE TITLE
Image caption anzeigen

### ISSUE THREAD

**Issue by diplomod** [diplomod/Geonova-new-#2]
Wie bei geo365

Außerdem Überschrift in der News gleich mit vergrößern (auf 60 px)

**Comment by lukassiedel** [comment]
done und live :)

**Comment by diplomod** [comment]
Cool. Kannst du das noch in der Schriftfarbe grau machen - wie bei geo365

**Comment by lukassiedel** [comment]
ist schon, das liegt nur am aktuallisieren vom browser. hatte mich auch erst gewundert.

**Comment by diplomod** [comment]
Läuft, merci
