### ISSUE TITLE
Count-Plugin löscht dauernd die Stats

### ISSUE THREAD

**Issue by diplomod** [diplomod/Geonova-new-#4]
ich krieg einen Vogel...

![screen shot 2016-06-13 at 10 43 51](https://cloud.githubusercontent.com/assets/7487883/16001711/faa2a5d2-3153-11e6-8cd2-500316941b00.png)

**Comment by lukassiedel** [comment]
sollte jetzt gehen

**Comment by lukassiedel** [comment]
ok mein fehler ich hab mich getäuscht. es löscht scheinbar wöchentlich

**Comment by lukassiedel** [comment]
jetzt hab ich den fehler gefunden. War durch uns selbst verursacht. Der tom hat ja damals eine Funktion geschrieben, um die Statistiken wöchentlich in eine CSV zu schreiben. und dabei hat er (offenbar beabsichtigt) die Counter immer zurückgesetzt. sollte jetzt nicht wieder passieren

**Comment by diplomod** [comment]
OK - werde ich ein paar tage beobachten, danke.

**Comment by lukassiedel** [comment]
diesen montag hat es nicht gelöscht. daher done würd ich sagen :)

**Comment by diplomod** [comment]
top, merci
