### ISSUE TITLE
Kann kein Image mehr bei Events hinzufügen

### ISSUE THREAD

**Issue by diplomod** [diplomod/Geonova-new-#6]
http://www.geonova.no/wp-admin/admin.php?page=events-manager&eme_admin_action=edit_event&event_id=47

![screen shot 2016-06-14 at 14 26 46](https://cloud.githubusercontent.com/assets/7487883/16042642/0c2e5bd2-323c-11e6-94b5-716acc404dd6.png)

**Comment by lukassiedel** [comment]
Das ganze ist erstmal gefixed. Ich musste eine nicht mehr funktionierende Autocomplete funktion rausnehmen, die aber die Funktion nicht beeinträchtigt. 
Allgemein hab ich gesehn, dass die googleMaps API-Version die da genutzt wird schon eine relativ alte ist. Ich würde das mal im Auge behalten das noch umzubauen. Dazu braucht man aber inzwischen einen (soweit ich weiß kostenfreien) Key für die Anwendung.
