### ISSUE TITLE
Layout News

### ISSUE THREAD

**Issue by diplomod** [diplomod/Geonova-new-#7]
Könnt ihr den Abstand zwischen Image Caption und 2nd headline etwas verringern?

![screen shot 2016-07-05 at 20 42 02](https://cloud.githubusercontent.com/assets/7487883/16595785/2dc5d656-42f1-11e6-91f1-c0aea38d9d8c.png)

zB hier: http://www.geonova.no/geobuzz/news-page/norsk-bergverksmuseum/

Außerdem: Das Datum des Postings anzeigen + Excerpt automatisch anzeigen:

![screen shot 2016-08-29 at 11 28 23](https://cloud.githubusercontent.com/assets/7487883/18047170/c0e5d296-6ddb-11e6-8b92-b394f6cff5aa.png)

**Comment by diplomod** [comment]
Abstand schaut auf dokuhl gut aus jetzt

Excerpt passt

Datum wir mir nicht ganz am rechten Rand, sondern in de Mitte zwischen Excerpt und rechtem Rand angezeigt:
![screen shot 2016-10-03 at 10 42 12](https://cloud.githubusercontent.com/assets/7487883/19031764/4461b780-8956-11e6-8bc2-3cb238bf71e3.png)

Anzeige Datum in Safari und Chrome gleich, unabhängig von Bildschrimgröße

**Comment by lukassiedel** [comment]
tatsächlich. sollte jetzt passen

**Comment by diplomod** [comment]
Passt
kann wegen mir auf Live

**Comment by diplomod** [comment]
Schaut gut aus.
